project:
  type: book

book:
  title: "GG3209 - Spatial Analysis with GIS"
  subtitle: "Second Part - Introduction to Python"
  author: "Fernando Benitez-Paez"
  date: last-modified
  favicon: "images/StA.png"
  downloads: [pdf]
  page-footer:
    background: light
    left: "2025, Fernando Benitez-Paez - SGSD - The University of St Andrews"
    right:
      - icon: github
        href: https://github.com/mfbenitezp
  sidebar:
    style: "floating"
    date-format: iso
    title: "{{< meta date >}}"
    collapse-level: 1  
  navbar:
    background: light
    search: true
    right:
      - text: "Home"
        href: index.qmd
      - intro.qmd
      - DataSources.qmd
  # Binder option removed; only Thebe enabled for in-browser execution
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Installation"
      chapters:
        - gg3209_install_guide.qmd
        - git_guide.qmd
    - part: "Lab No 1: Introduction to Python"
      chapters:
        - Lab_1/Lab_1.qmd
    - part: "Lab No 2: Python Basics"
      chapters:
        - Lab_2/Lab_2_1.qmd
        - Lab_2/Lab_2_2.qmd
    - part: "Assignments"
      chapters:
        - assignments/lab_1_installation.qmd
    - DataSources.qmd
    - troubleshooting.qmd

format:
  html:
    respect-user-color-scheme: true
    mermaid:
      theme: default
    theme:
      light: cosmo
      dark:
        - theme-dark.scss
    #code-tools: true
    thebe: true
  pdf:
    documentclass: scrbook


editor: visual
date: last-modified
execute:
  freeze: auto
